pr:
  - master
variables:
  API_KEY: $(apiKey)
jobs:
  - job: terraform_plan_json
    displayName: Terraform plan JSON
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(API_KEY)
      - bash: >-
          infracost breakdown --path=examples/terraform-plan-json/code/plan.json
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - bash: >-
          infracost output --path=/tmp/infracost.json
          --format=azure-repos-comment --show-skipped
          --out-file=/tmp/infracost_comment.md
        displayName: Generate Infracost comment
      - bash: >-
          diff ./testdata/terraform_plan_json_comment_golden.md
          /tmp/infracost_comment.md
        displayName: Check the comment
        condition: ne(variables['UPDATE_GOLDEN_FILES'], 'true')
      - bash: >-
          cp /tmp/infracost_comment.md
          ./testdata/terraform_plan_json_comment_golden.md
        displayName: Update the golden comment file
        condition: eq(variables['UPDATE_GOLDEN_FILES'], 'true')
