pr:
  - master
name: Infracost.InfracostAzureDevops.Examples.Test
jobs:
  - job: conftest
    displayName: Conftest
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: >
          INSTALL_LOCATION="$(Build.SourcesDirectory)/conftest"


          mkdir -p ${INSTALL_LOCATION}


          curl -sL -o /tmp/conftest.tar.gz
          "https://github.com/open-policy-agent/conftest/releases/download/v0.30.0/conftest_0.30.0_Linux_x86_64.tar.gz"


          tar -xzf /tmp/conftest.tar.gz -C ${INSTALL_LOCATION}


          chmod +x ${INSTALL_LOCATION}/conftest


          echo "##vso[task.setvariable
          variable=PATH;]$(PATH):${INSTALL_LOCATION}"
        displayName: Setup Conftest
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown --path=examples/conftest/code/plan.json
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - bash: >-
          infracost output --path=/tmp/infracost.json
          --format=azure-repos-comment --show-skipped
          --out-file=/tmp/infracost_comment.md
        displayName: Generate Infracost comment
      - bash: conftest test --policy examples/conftest/policy /tmp/infracost.json
        displayName: Check Conftest Policies
  - job: multi_project_config_file
    displayName: Multi-project config file
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown
          --config-file=examples/multi-project/code/infracost.yml --format=json
          --out-file=/tmp/infracost.json
        displayName: Run Infracost
        env:
          DEV_AWS_ACCESS_KEY_ID: $(exampleDevAwsAccessKeyId)
          DEV_AWS_SECRET_ACCESS_KEY: $(exampleDevAwsSecretAccessKey)
          PROD_AWS_ACCESS_KEY_ID: $(exampleProdAwsAccessKeyId)
          PROD_AWS_SECRET_ACCESS_KEY: $(exampleProdAwsSecretAccessKey)
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: >-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md

          diff ./testdata/multi_project_config_file_comment_golden.md
          /tmp/infracost_comment.md
        displayName: Check the comment
  - job: multi_project_matrix
    displayName: Multi-project matrix
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        dev:
          AWS_ACCESS_KEY_ID: $(exampleDevAwsAccessKeyId)
          AWS_SECRET_ACCESS_KEY: $(exampleDevAwsSecretAccessKey)
          DIR: dev
        prod:
          AWS_ACCESS_KEY_ID: $(exampleProdAwsAccessKeyId)
          AWS_SECRET_ACCESS_KEY: $(exampleProdAwsSecretAccessKey)
          DIR: prod
      maxParallel: 2
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown --path=examples/multi-project/code/$(DIR)
          --format=json --out-file=/tmp/infracost_$(DIR).json
        displayName: Run Infracost
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      - task: PublishBuildArtifacts@1
        displayName: Upload Infracost breakdown
        inputs:
          PathtoPublish: /tmp/infracost_$(DIR).json
          ArtifactName: infracost_jsons
          publishLocation: Container
  - job: multi_project_matrix_merge
    displayName: Multi-project matrix merge
    pool:
      vmImage: ubuntu-latest
    dependsOn:
      - multi_project_matrix
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          downloadType: single
          artifactName: infracost_jsons
          downloadPath: $(System.DefaultWorkingDirectory)
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >
          infracost output --path="infracost_jsons/*.json" --format=json
          --out-file=/tmp/infracost_combined.json
        displayName: Combine the results
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost_combined.json
          behavior: update
          dryRun: true
      - bash: >-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md

          diff ./testdata/multi_project_matrix_merge_comment_golden.md
          /tmp/infracost_comment.md
        displayName: Check the comment
  - job: multi_terraform_workspace_config_file
    displayName: Multi-Terraform workspace config file
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >
          infracost breakdown
          --config-file=examples/multi-terraform-workspace/code/infracost.yml
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
        env:
          DEV_AWS_ACCESS_KEY_ID: $(exampleDevAwsAccessKeyId)
          DEV_AWS_SECRET_ACCESS_KEY: $(exampleDevAwsSecretAccessKey)
          PROD_AWS_ACCESS_KEY_ID: $(exampleProdAwsAccessKeyId)
          PROD_AWS_SECRET_ACCESS_KEY: $(exampleProdAwsSecretAccessKey)
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: >-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md

          diff
          ./testdata/multi_terraform_workspace_config_file_comment_golden.md
          /tmp/infracost_comment.md
        displayName: Check the comment
  - job: open_policy_agent
    displayName: Open Policy Agent
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >
          INSTALL_LOCATION="$(Build.SourcesDirectory)/bin"

          mkdir -p ${INSTALL_LOCATION}


          wget -O ${INSTALL_LOCATION}/opa
          https://openpolicyagent.org/downloads/v${OPA_VERSION}/opa_linux_amd64_static

          chmod +x ${INSTALL_LOCATION}/opa


          echo "##vso[task.setvariable
          variable=PATH;]$(PATH):${INSTALL_LOCATION}"
        displayName: Setup OPA
        env:
          OPA_VERSION: 0.35.0
      - bash: >-
          infracost breakdown --path=examples/opa/code/plan.json --format=json
          --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - bash: >-
          opa eval --input /tmp/infracost.json -d
          examples/opa/policy/policy.rego --format pretty "data.infracost.deny"
          | tee /tmp/opa.out
        displayName: Run OPA
      - bash: |
          denyReasons=$(</tmp/opa.out)
          if [ "$denyReasons" != "[]" ]; then
            echo "##vso[task.logissue type=error]Policy check failed"
            echo "##vso[task.logissue type=error]$denyReasons"
            echo "##vso[task.complete result=Failed;]DONE"
          else
            echo "Policy check passed."
          fi
        displayName: Check Policies
  - job: private_terraform_module
    displayName: Private Terraform module
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
      - bash: >
          mkdir -p .ssh

          echo "$(echo $GIT_SSH_KEY_BASE_64 | base64 -d)" > .ssh/git_ssh_key

          chmod 400 .ssh/git_ssh_key

          echo "##vso[task.setvariable variable=GIT_SSH_COMMAND;]ssh -i
          $(pwd)/.ssh/git_ssh_key -o 'StrictHostKeyChecking=no'"
        displayName: Add git SSH key
        env:
          GIT_SSH_KEY_BASE_64: $(gitSshKeyBase64)
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >
          infracost breakdown --path=examples/private-terraform-module/code
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: >-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md

          diff ./testdata/private_terraform_module_comment_golden.md
          /tmp/infracost_comment.md
        displayName: Check the comment
  - job: sentinel
    displayName: Sentinel
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >
          INSTALL_LOCATION="$(Build.SourcesDirectory)/sentinel"

          mkdir -p ${INSTALL_LOCATION}


          curl -o sentinel.zip
          https://releases.hashicorp.com/sentinel/0.18.4/sentinel_0.18.4_linux_amd64.zip

          unzip -d ${INSTALL_LOCATION} sentinel.zip


          echo "##vso[task.setvariable
          variable=PATH;]$(PATH):${INSTALL_LOCATION}"
        displayName: Setup Sentinel
      - bash: >-
          infracost breakdown --path=examples/sentinel/code/plan.json
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - bash: >-
          sentinel apply -global breakdown="$(cat /tmp/infracost.json)"
          examples/sentinel/policy/policy.policy | tee /tmp/sentinel.out
        displayName: Run Sentinel
      - bash: |
          result=$(</tmp/sentinel.out)

          if [ "$result" != "Pass - policy.policy" ]; then
            echo "##vso[task.logissue type=error]Policy check failed"
            echo "##vso[task.logissue type=error]$result"
            echo "##vso[task.complete result=Failed;]DONE"
          else
            echo "Policy check passed."
          fi
        displayName: Check Policies
  - job: slack
    displayName: Slack
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown --path examples/slack/code/plan.json --format json
          --out-file /tmp/infracost.json
        displayName: Run Infracost
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: |-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md
          diff ./testdata/slack_comment_golden.md /tmp/infracost_comment.md
        displayName: Check the comment
      - bash: >-
          infracost output --path /tmp/infracost.json --format slack-message
          --show-skipped --out-file /tmp/slack-message.json
        displayName: Generate Slack message
      - bash: >-
          diff ./testdata/slack_slack_message_golden.json
          /tmp/slack-message.json
        displayName: Check the Slack message
  - job: terraform_cloud_enterprise
    displayName: Terraform Cloud/Enterprise
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown --path=examples/terraform-cloud-enterprise/code
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
        env:
          INFRACOST_TERRAFORM_CLOUD_TOKEN: $(tfcToken)
          INFRACOST_TERRAFORM_CLOUD_HOST: app.terraform.io
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: >-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md

          diff ./testdata/terraform_cloud_enterprise_comment_golden.md
          /tmp/infracost_comment.md
        displayName: Check the comment
  - job: terraform_directory
    displayName: Terraform Directory
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown --path=examples/terraform-directory/code
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: >-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md

          diff ./testdata/terraform_directory_comment_golden.md
          /tmp/infracost_comment.md
        displayName: Check the comment
  - job: terraform_plan_json
    displayName: Terraform plan JSON
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown --path=examples/terraform-plan-json/code/plan.json
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: >-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md

          diff ./testdata/terraform_plan_json_comment_golden.md
          /tmp/infracost_comment.md
        displayName: Check the comment
  - job: terragrunt
    displayName: Terragrunt
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
      - bash: >
          INSTALL_LOCATION="$(Build.SourcesDirectory)/bin"

          mkdir -p ${INSTALL_LOCATION}


          curl -sL
          "https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64"
          > ${INSTALL_LOCATION}/terragrunt

          chmod +x ${INSTALL_LOCATION}/terragrunt


          echo "##vso[task.setvariable
          variable=PATH;]$(PATH):${INSTALL_LOCATION}"
        displayName: Setup Terragrunt
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown --path=examples/terragrunt/code --format=json
          --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: |-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md
          diff ./testdata/terragrunt_comment_golden.md /tmp/infracost_comment.md
        displayName: Check the comment
  - job: thresholds
    displayName: Thresholds
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(infracostApiKey)
      - bash: >-
          infracost breakdown --path=examples/thresholds/code/plan.json
          --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost
      - bash: >
          # Read the breakdown JSON and get costs

          past=$(cat /tmp/infracost.json | jq -r "(.pastTotalMonthlyCost // 0) |
          tonumber")

          current=$(cat /tmp/infracost.json | jq -r "(.totalMonthlyCost // 0) |
          tonumber")

          cost_change=$(cat /tmp/infracost.json | jq -r "(.diffTotalMonthlyCost
          // 0) | tonumber")


          percent_change=999 # default to a high number so we post a comment if
          there's no past cost


          if [ "$past" != "0" ]; then
            percent_change=$(echo "100 * (($current - $past) / $past)" | bc -l)
          fi


          absolute_percent_change=$(echo "${percent_change#-}")


          echo "past: ${past}"

          echo "current: ${current}"

          echo "cost_change: ${cost_change}"

          echo "absolute_cost_change: ${cost_change#-}"

          echo "percent_change: ${percent_change}"

          echo "absolute_percent_change: ${absolute_percent_change}"


          # Set the calculated diffs as outputs to be used in future tasks/steps

          echo "##vso[task.setvariable
          variable=absolutePercentChange;]${absolute_percent_change}"

          echo "##vso[task.setvariable
          variable=percentChange;]${percent_change}"

          echo "##vso[task.setvariable
          variable=absoluteCostChange;]${cost_change#-}"

          echo "##vso[task.setvariable variable=costChange;]${cost_change}"
        displayName: Calculate Cost Change
      - task: InfracostComment@0
        displayName: Post the comment
        condition: lt(1, variables.absolutePercentChange)
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
          dryRun: true
      - bash: |-
          echo $(Infracost.Comment.Out) > /tmp/infracost_comment.md
          diff ./testdata/thresholds_comment_golden.md /tmp/infracost_comment.md
        displayName: Check the comment
