trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: azure-infracost-tasks

stages:
  - stage: Package_extension_and_publish_build_artifacts
    jobs:
      - job:
        steps:
          - task: TfxInstaller@3
            inputs:
              version: 'v0.7.x'
          - task: Npm@1
            displayName: Install InfracostSetup dependencies
            inputs:
              command: 'install'
              workingDir: 'tasks/InfracostSetup'
          - task: Bash@3
            displayName: Compile InfracostSetup Javascript
            inputs:
              targetType: 'inline'
              script: |
                cd tasks/InfracostSetup
                npm run build
          - task: Npm@1
            displayName: Install InfracostComment dependencies
            inputs:
              command: 'install'
              workingDir: 'tasks/InfracostComment'
          - task: Bash@3
            displayName: Compile InfracostComment Javascript
            inputs:
              targetType: 'inline'
              script: |
                cd tasks/InfracostComment
                npm run build
          - task: PackageAzureDevOpsExtension@3
            inputs:
              rootFolder: '$(System.DefaultWorkingDirectory)'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              patternManifest: 'vss-extension.json'
              extensionVisibility: '$(ExtensionVisibility)'
              extensionPricing: 'free'
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              Contents: '**/*.vsix'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(ArtifactName)'
              publishLocation: 'Container'
  - stage: Download_build_artifacts_and_publish_the_extension
    jobs:
      - job:
        steps:
          - task: TfxInstaller@3
            inputs:
              version: 'v0.7.x'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: '$(ArtifactName)'
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: PublishAzureDevOpsExtension@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: '$(ServiceConnection)'
              fileType: 'vsix'
              vsixFile: '$(ArtifactName)/$(PublisherID).*.vsix'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              updateTasksVersion: false
              extensionVisibility: '$(ExtensionVisibility)'
              extensionPricing: 'free'
